services:
  algaposts-rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: algaposts-rabbitmq
    restart: no
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - ./.docker/rabbitmq:/var/lib/rabbitmq
      - ./configs/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins